# 使用 Claude Sonnet 4 模型
model: anthropic/claude-sonnet-4-20250514
editor-model: anthropic/claude-sonnet-4-20250514

# 自动生成最小 diff 的提交
auto-commits: true
dirty-commits: false

# 写明确的提交说明（自测/回滚）
commit-prompt: |
  写清：变更目的、修改文件、如何自测（make/curl/kubectl）、如何回滚（rollout undo 或 git revert）。
  严格最小化 diff，禁止无关格式化/重排。
