apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - patch-deploy.yaml
  - patch-image.yaml
  - patch-clear-cmd.yaml
  - patch-cmd.yaml
