apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb-composer-worker
  namespace: orchestrator
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: worker
          # 初始使用已知存在的digest，CI会自动更新这里
          image: ghcr.io/bbk66669/kingbrain/orchestrator@sha256:b7caa103cdeb5397081ebc0203971a69a24a2dd556b983971aabc5aa2996f5ee
