apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb-orchestrator
  namespace: orchestrator
spec:
  template:
    metadata:
      labels:
        kb-signed: "true"
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: api
          image: ghcr.io/bbk66669/kingbrain/orchestrator@sha256:b7caa103cdeb5397081ebc0203971a69a24a2dd556b983971aabc5aa2996f5ee
