apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb-orchestrator
  namespace: orchestrator
spec:
  template:
    metadata:
      labels:
        kb-signed: "true"
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: api
          image: ghcr.io/bbk66669/kingbrain/orchestrator@sha256:f51790cccc73f92f04ce5d98e42dbf8d7dde9bbc6201dc9d1f2c4427a7dc3450
